name: surf
description: Project for testing Surf plugins
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  mwwm: ^2.0.0
  provider: ^6.0.0
  surf_mwwm: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_lints: ^1.0.0
  surf_lint_rules: ^1.0.0

flutter:
  uses-material-design: true
